import Navbar from '../components/Admin/Navbar';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
import '../globals.css';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={inter.className}>
      <body className='dark'>
        <div className='bg-black h-screen overflow-y-scroll  pb-36'>
          <Navbar />
          <div className='ml-16 overflow-hidden w-[calc(100vw-5rem)] pl-4 text-white '>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
