import Navbar from '../components/Admin/Navbar';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
import '../globals.css';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <div className='bg-black h-screen overflow-y-scroll bg_grid pb-36'>
          <Navbar />
          <div className='p-2 lg:pl-52 '>
            <div className='mx-auto max-w-8xl space-y-8 px-2 pt-20 lg:px-8 lg:py-8'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
