name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main # Change if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Node.js (needed for Wrangler CLI)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install latest Wrangler globally
      - name: Install Wrangler CLI
        run: npm install -g wrangler

      # Deploy to Cloudflare Workers
      - name: Deploy Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: wrangler deploy
